export const CommentActionTypes = {
  COMMENT_INDEX_REQUEST: 'COMMENT_INDEX_REQUEST',
  COMMENT_INDEX_SUCCESS: 'COMMENT_INDEX_SUCCESS',
  COMMENT_INDEX_FAILURE: 'COMMENT_INDEX_FAILURE',
  COMMENT_POST_REQUEST: 'COMMENT_POST_REQUEST',
  COMMENT_POST_SUCCESS: 'COMMENT_POST_SUCCESS',
  COMMENT_POST_FAILURE: 'COMMENT_POST_FAILURE',
  COMMENT_DELETE_REQUEST: 'COMMENT_DELETE_REQUEST',
  COMMENT_DELETE_SUCCESS: 'COMMENT_DELETE_SUCCESS',
  COMMENT_DELETE_FAILURE: 'COMMENT_DELETE_FAILURE',
}
