export const FeedActionTypes = {
  FEED_INDEX_REQUEST: 'FEED_REQUEST',
  FEED_INDEX_SUCCESS: 'FEED_SUCCESS',
  FEED_INDEX_FAILURE: 'FEED_FAILURE',
  FEED_POST_REQUEST: 'FEED_POST_REQUEST',
  FEED_POST_SUCCESS: 'FEED_POST_SUCCESS',
  FEED_POST_FAILURE: 'FEED_POST_FAILURE',
  FEED_DELETE_REQUEST: 'FEED_DELETE_REQUEST',
  FEED_DELETE_SUCCESS: 'FEED_DELETE_SUCCESS',
  FEED_DELETE_FAILURE: 'FEED_DELETE_FAILURE',
}
